# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""SQL Lab permalink commands.

Re-exports of the existing permalink command surface (owned by W1) so
that ``from superset.commands.sqllab import CreateSqlLabPermalinkCommand``
keeps working after we restructured ``commands/sqllab.py`` into a
package. The actual implementations live below — they are unchanged
from the previous monolithic file.
"""

from __future__ import annotations

import json  # noqa: TID251 -- json is fine for hashids round-trips
import logging
from typing import Any, TYPE_CHECKING

from superset.commands.base import AsyncBaseCommand
from superset.exceptions import CommandInvalidError, ObjectNotFoundError

if TYPE_CHECKING:
    from superset.db.daos.key_value import AsyncKeyValueDAO

logger = logging.getLogger(__name__)


class CreateSqlLabPermalinkCommand(AsyncBaseCommand[str]):
    """Create a SQL Lab permalink — deterministic UUID + hashids id."""

    def __init__(
        self,
        dao: "AsyncKeyValueDAO",
        state: dict[str, Any],
        user_id: int | None = None,
    ) -> None:
        self._dao = dao
        self._state = state
        self._user_id = user_id

    async def validate(self) -> None:
        pass

    async def run(self) -> str:
        from superset.key_value.shared_entries import get_permalink_salt
        from superset.key_value.types import KeyValueResource, SharedKey
        from superset.key_value.utils import (
            encode_permalink_key,
            get_deterministic_uuid,
        )

        session = self._dao.session
        salt = await get_permalink_salt(session, SharedKey.SQLLAB_PERMALINK_SALT)
        deterministic_uuid = get_deterministic_uuid(salt, (self._user_id, self._state))

        encoded = json.dumps(self._state, sort_keys=True).encode("utf-8")
        existing = await self._dao.get_entry_by_key(
            resource=KeyValueResource.SQLLAB_PERMALINK.value,
            key=deterministic_uuid,
        )
        if existing is None:
            entry = await self._dao.create_entry(
                resource=KeyValueResource.SQLLAB_PERMALINK.value,
                value=encoded,
                key=deterministic_uuid,
            )
            await session.flush()
        else:
            existing.value = encoded
            entry = existing

        if entry.id is None:
            raise RuntimeError("SQL Lab permalink entry missing autogenerated id")
        return encode_permalink_key(key=entry.id, salt=salt)


class GetSqlLabPermalinkCommand(AsyncBaseCommand[dict[str, Any]]):
    def __init__(self, dao: "AsyncKeyValueDAO", key: str) -> None:
        self._dao = dao
        self._key = key

    async def validate(self) -> None:
        if not self._key:
            raise CommandInvalidError("key is required")

    async def run(self) -> dict[str, Any]:
        from superset.key_value.exceptions import KeyValueParseKeyError
        from superset.key_value.shared_entries import get_permalink_salt
        from superset.key_value.types import KeyValueResource, SharedKey
        from superset.key_value.utils import decode_permalink_id

        session = self._dao.session
        salt = await get_permalink_salt(session, SharedKey.SQLLAB_PERMALINK_SALT)
        try:
            entry_id = decode_permalink_id(self._key, salt=salt)
        except (KeyValueParseKeyError, Exception) as ex:  # noqa: BLE001
            raise ObjectNotFoundError("SqlLabPermalink", self._key) from ex

        value = await self._dao.get_value_by_key(
            resource=KeyValueResource.SQLLAB_PERMALINK.value,
            key=entry_id,
        )
        if value is None:
            raise ObjectNotFoundError("SqlLabPermalink", self._key)
        if isinstance(value, dict):
            return value
        return {"value": value}
