# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Async port of ``superset_old/commands/dashboard/permalink/create.py``.

The store layout matches the original Superset:

* Internally the entry is keyed by a deterministic UUID
  (``uuid3(salt, (user_id, value))``) so the same dashboard+state for
  the same user always reuses the same row.
* Externally the URL key is the auto-generated integer ``id`` of the
  entry, encoded with hashids using a per-install salt persisted in
  the ``app`` resource. ``GET /dashboard/permalink/{key}`` decodes
  that hashids string back to the integer id and looks the entry up.
"""

from __future__ import annotations

import json  # noqa: TID251
from typing import Any, TYPE_CHECKING

from sqlalchemy.ext.asyncio import AsyncSession

from superset.commands.base import AsyncBaseCommand
from superset.key_value.shared_entries import get_permalink_salt
from superset.key_value.types import KeyValueResource, SharedKey
from superset.key_value.utils import encode_permalink_key, get_deterministic_uuid

if TYPE_CHECKING:
    from superset.db.daos.key_value import AsyncKeyValueDAO


class CreateDashboardPermalinkCommand(AsyncBaseCommand[str]):
    """Get or create a permalink key for the dashboard.

    The same dashboard_id and state for the same user will return the
    same permalink — 1:1 with the original sync command.
    """

    def __init__(
        self,
        dao: AsyncKeyValueDAO,
        dashboard_id: int,
        state: dict[str, Any],
        dashboard_uuid: str | None = None,
        user_id: int | None = None,
    ) -> None:
        self._dao = dao
        self._dashboard_id = dashboard_id
        self._state = state
        self._dashboard_uuid = dashboard_uuid
        self._user_id = user_id

    async def validate(self) -> None:
        pass

    async def run(self) -> str:
        # Use UUID when available; fall back to int id for backwards compat
        dash_id_value: str | int = (
            self._dashboard_uuid if self._dashboard_uuid else self._dashboard_id
        )
        payload = {
            "dashboardId": dash_id_value,
            "state": self._state,
        }
        session: AsyncSession = self._dao.session
        salt = await get_permalink_salt(session, SharedKey.DASHBOARD_PERMALINK_SALT)
        # Deterministic UUID derived from (salt, (user_id, value)) so the
        # same payload for the same user always upserts the same row —
        # matches CreateDashboardPermalinkCommand at
        # superset_old/commands/dashboard/permalink/create.py:74-80.
        deterministic_uuid = get_deterministic_uuid(salt, (self._user_id, payload))

        existing = await self._dao.get_entry_by_key(
            resource=KeyValueResource.DASHBOARD_PERMALINK.value,
            key=deterministic_uuid,
        )
        encoded = json.dumps(payload).encode("utf-8")
        if existing is None:
            entry = await self._dao.create_entry(
                resource=KeyValueResource.DASHBOARD_PERMALINK.value,
                value=encoded,
                key=deterministic_uuid,
            )
            await session.flush()
        else:
            existing.value = encoded  # type: ignore[assignment]
            entry = existing

        if entry.id is None:
            raise RuntimeError("Permalink entry missing autogenerated id")
        return encode_permalink_key(key=int(entry.id), salt=salt)
