# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Async QueryContextProcessor — processes QueryContext payloads asynchronously.

All request-scoped globals (current_app.config, security_manager,
cache_manager, AnnotationLayerDAO) are replaced by constructor-injected
dependencies.

All utility imports use superset.utils modules — no superset dependency.
"""

from __future__ import annotations

import asyncio
import copy
import inspect
import logging
import re
from typing import Any, ClassVar, TYPE_CHECKING, TypedDict

import numpy as np
import pandas as pd

from superset.common.query_object import AsyncQueryObject
from superset.typing import DatasourceProtocol
from superset.utils import pandas_postprocessing

if TYPE_CHECKING:
    from superset.common.query_context import AsyncQueryContext
    from superset.config import SupersetSettings

logger = logging.getLogger(__name__)

OFFSET_JOIN_COLUMN_SUFFIX = "__offset_join_column_"
R_SUFFIX = "__right_suffix"
DTTM_ALIAS = "__timestamp"
_MAX_RECURSION_DEPTH = 2

# CSV formula injection prevention
_NEGATIVE_NUMBER_RE = re.compile(r"^-[0-9.]+$")
_PROBLEMATIC_CHARS_RE = re.compile(r'^(?:"{2}|\s{1,})(?=[\-@+|=%])|^[\-@+|=%]')


def _escape_csv_value(value: str) -> str:
    """Escape values that could trigger formula injection in spreadsheets."""
    needs_escaping = _PROBLEMATIC_CHARS_RE.match(value) is not None
    is_negative_number = _NEGATIVE_NUMBER_RE.match(value) is not None
    if needs_escaping and not is_negative_number:
        value = value.replace("|", "\\|")
        value = "'" + value
    return value


def _df_to_escaped_csv(df: pd.DataFrame, **kwargs: Any) -> str:
    """Convert DataFrame to CSV with formula injection escaping."""

    def _escape(v: Any) -> str | Any:
        return _escape_csv_value(v) if isinstance(v, str) else v

    df = df.rename(columns=_escape)
    for name, column in df.items():
        if column.dtype == np.dtype(object):
            for idx, value in enumerate(column.values):
                if isinstance(value, str):
                    df.at[idx, name] = _escape_csv_value(value)
    return df.to_csv(index=False, escapechar="\\", **kwargs)


class CachedTimeOffset(TypedDict):
    df: pd.DataFrame
    queries: list[str]
    cache_keys: list[str | None]


def _generate_cache_key(cache_dict: dict[str, Any], prefix: str = "") -> str:
    """Generate a deterministic cache key from a dict."""
    from superset.utils.hashing import md5_sha_from_dict
    from superset.utils.json import json_int_dttm_ser

    hash_val = md5_sha_from_dict(cache_dict, default=json_int_dttm_ser, ignore_nan=True)
    return f"{prefix}{hash_val}"


async def load_cached_query_context_form(
    cache_manager: Any,
    cache_key: str,
) -> dict[str, Any] | None:
    """Load + unpickle a cached query-context *form* by ``cache_key``.

    Inverse of :meth:`AsyncQueryContextProcessor._cache_set` for the
    query-context form written by :meth:`AsyncQueryContextProcessor.get_payload`
    (``{"data": form_data}``, pickle-serialized).

    :param cache_manager: an async cache manager (e.g.
        ``app.state.cache_manager.cache``) exposing ``async get(key)`` that
        returns the pickle bytes written by ``_cache_set``.
    :param cache_key: the ``qc-`` prefixed key generated by
        ``_generate_context_cache_key``.
    :returns: the cached ``form_data`` dict, or ``None`` when the entry is
        absent or malformed.
    """
    if cache_manager is None or not cache_key:
        return None
    try:
        getter = cache_manager.get(cache_key)
        raw = await getter if inspect.isawaitable(getter) else getter
    except Exception:  # noqa: BLE001
        logger.warning(
            "Cache get failed for query-context form key %s", cache_key, exc_info=True
        )
        return None
    if raw is None:
        return None
    value: Any = raw
    if isinstance(raw, (bytes, bytearray)):
        import pickle  # noqa: S403 — cache compat with _cache_set pickle format

        try:
            value = pickle.loads(raw)  # noqa: S301
        except (pickle.UnpicklingError, TypeError, EOFError, ValueError):
            logger.warning(
                "Failed to unpickle query-context form for key %s", cache_key
            )
            return None
    if isinstance(value, dict) and "data" in value:
        data = value["data"]
        return data if isinstance(data, dict) else None
    return None


# Cache-key prefix the legacy ``load_explore_json_into_cache`` Celery task
# writes its entry under.  The default async cache slot (``AsyncCacheManager``)
# issues an unprefixed ``redis.get``, but the task writes via the
# upstream-cache-style ``superset_cache:`` prefix (raw sync Redis), so the read
# must try the prefixed key first.
_FLASK_CACHE_KEY_PREFIX = "superset_cache:"


async def load_cached_explore_form(
    cache_manager: Any,
    cache_key: str,
) -> dict[str, Any] | None:
    """Load the ``{form_data, response_type}`` cached by the explore task.

    Inverse of the cache write in
    :func:`superset.tasks.async_queries.load_explore_json_into_cache`, which
    stores ``{"form_data": ..., "response_type": ...}`` (pickle-serialized)
    under the ``ejr-`` cache key.  Used by the legacy
    ``GET /superset/explore_json/data/<cache_key>`` endpoint.

    The task writes via raw sync Redis under the upstream-cache-style
    ``superset_cache:<cache_key>`` key, while the default async cache slot
    (``AsyncCacheManager.get``) issues an unprefixed ``redis.get`` — so we try
    the prefixed key first and fall back to the bare key.

    On a miss we return ``None`` so the caller can raise the project's 404.

    :param cache_manager: an async/sync cache slot exposing ``get(key)``
        (e.g. ``superset.extensions.cache_manager.cache``).
    :param cache_key: the ``ejr-`` prefixed key from the result_url.
    :returns: the cached value dict, or ``None`` when absent / malformed.
    """
    if cache_manager is None or not cache_key:
        return None

    for key in (f"{_FLASK_CACHE_KEY_PREFIX}{cache_key}", cache_key):
        try:
            getter = cache_manager.get(key)
            raw = await getter if inspect.isawaitable(getter) else getter
        except Exception:  # noqa: BLE001
            logger.warning(
                "Cache get failed for explore form key %s", key, exc_info=True
            )
            raw = None
        if raw is None:
            continue
        value: Any = raw
        if isinstance(raw, (bytes, bytearray)):
            import pickle  # noqa: S403 — cache compat with the Celery task

            try:
                value = pickle.loads(raw)  # noqa: S301
            except (pickle.UnpicklingError, TypeError, EOFError, ValueError):
                logger.warning("Failed to unpickle explore form for key %s", key)
                continue
        if isinstance(value, dict):
            return value
    return None


class AsyncQueryContextProcessor:
    """Processes QueryContext payloads asynchronously.

    All request-scoped globals are replaced by constructor-injected
    dependencies:
      - current_app.config["ROW_LIMIT"] -> self._settings.row_limit
      - current_app.config["CACHE_DEFAULT_TIMEOUT"]
      - current_app.config["DATA_CACHE_CONFIG"] -> self._settings.data_cache_config
      - security_manager -> self._security_manager
      - cache_manager -> self._cache_manager
      - AnnotationLayerDAO -> self._annotation_dao
    """

    cache_type: ClassVar[str] = "df"
    enforce_numerical_metrics: ClassVar[bool] = True

    def __init__(
        self,
        datasource: DatasourceProtocol,
        settings: SupersetSettings,
        security_manager: Any,
        user: Any = None,
        cache_manager: Any | None = None,
        annotation_dao: Any | None = None,
        chart_dao: Any | None = None,
        query_context: AsyncQueryContext | None = None,
        _recursion_depth: int = 0,
    ) -> None:
        self._datasource = datasource
        self._settings = settings
        self._security_manager = security_manager
        self._user = user
        self._cache_manager = cache_manager
        self._annotation_dao = annotation_dao
        self._chart_dao = chart_dao
        self._query_context = query_context
        self._recursion_depth = _recursion_depth

    async def _ensure_totals_available(  # noqa: C901
        self, query_objects: list[AsyncQueryObject]
    ) -> None:
        """Find the totals query and inject computed totals into contribution ops.

        Finds the totals query (no columns, has metrics, no post-processing),
        executes it, and injects the totals dict into contribution operations'
        options.
        """
        contribution_ops: list[dict[str, Any]] = []
        for qo in query_objects:
            for pp in qo.post_processing:
                if pp.get("operation") == "contribution":
                    contribution_ops.append(pp)

        if not contribution_ops:
            return

        totals_query: AsyncQueryObject | None = None
        for qo in query_objects:
            if not qo.columns and qo.metrics and not qo.post_processing:
                totals_query = qo
                break

        if totals_query is None:
            return

        totals_query.row_limit = None

        from superset.exceptions import QueryObjectValidationError

        try:
            result = await self._get_query_result(totals_query)
            # Surface a failed totals query instead of silently using empty
            # totals (→ wrong contribution %).
            if result.get("status") in ("error", "failed") or result.get(
                "error_message"
            ):
                raise QueryObjectValidationError(
                    result.get("error_message") or "Contribution totals query failed"
                )
            totals_df = result.get("df", pd.DataFrame())
            if not totals_df.empty:
                # Use column sums, not iloc[0] — totals query may return
                # multiple rows if there are no groupby columns
                totals_dict = totals_df.sum(numeric_only=True).to_dict()
                for pp in contribution_ops:
                    options = pp.get("options", {})
                    options["contribution_totals"] = totals_dict
                    pp["options"] = options
        except QueryObjectValidationError:
            # Propagate a genuine query failure (caught by ``get_payload`` →
            # command → 400); only unexpected errors below are best-effort.
            raise
        except Exception:  # noqa: BLE001
            logger.warning("Failed to compute totals for contribution", exc_info=True)

    async def get_payload(
        self,
        query_objects: list[AsyncQueryObject],
        force: bool = False,
        cache_query_context: bool = False,
        force_cached: bool = False,
    ) -> dict[str, Any]:
        """Main entry point — processes all query objects, returns payload.

        Dispatches based on each query_object's result_type:
          - "columns"        — datasource column metadata, no query executed
          - "timegrains"     — available time grains, no query executed
          - "query"          — build SQL but don't execute
          - "samples"        — raw rows without metrics/filters/time window
          - "drill_detail"   — like samples but keeps the time filter and
                               orders by the first column
          - "results"        — execute without post-processing
          - "post_processed" — full results (post-processing applied later by
                               the chart context), same as "full"
          - "full" (default) — execute, normalize, and post-process
        """
        await self._ensure_totals_available(query_objects)
        # ``result_type`` lives on the query context, not on the query object.
        # Fall back to the context value when the per-query override is unset.
        ctx_result_type = (
            getattr(self._query_context, "result_type", None)
            if self._query_context is not None
            else None
        )
        query_results = []
        for qo in query_objects:
            result_type = getattr(qo, "result_type", None) or ctx_result_type or "full"

            if result_type == "columns":
                result = self._get_columns()
            elif result_type == "timegrains":
                result = self._get_timegrains()
            elif result_type == "query":
                result = await self._get_query_only(qo)
            elif result_type == "samples":
                result = await self._get_samples(
                    qo, force=force, force_cached=force_cached
                )
            elif result_type == "drill_detail":
                result = await self._get_drill_detail(
                    qo, force=force, force_cached=force_cached
                )
            elif result_type == "results":
                result = await self.get_df_payload(
                    qo,
                    force=force,
                    force_cached=force_cached,
                    skip_post_processing=True,
                )
            elif result_type in ("full", "post_processed"):
                result = await self.get_df_payload(
                    qo,
                    force=force,
                    force_cached=force_cached,
                )
            else:
                # Unrecognized result types raise a validation error.
                from superset.exceptions import QueryObjectValidationError
                from superset.i18n import _

                raise QueryObjectValidationError(
                    _(
                        "Invalid result type: %(result_type)s",
                        result_type=result_type,
                    )
                )
            query_results.append(result)

        return_value: dict[str, Any] = {"queries": query_results}

        if cache_query_context and self._cache_manager is not None:
            cache_key = self._generate_context_cache_key()
            await self._cache_set(
                cache_key,
                {"data": self._query_context.form_data},  # type: ignore[union-attr]
                self._get_cache_timeout(),
            )
            return_value["cache_key"] = cache_key

        return return_value

    def _get_columns(self) -> dict[str, Any]:
        """Return datasource column metadata without executing a query."""
        from superset.typing import GenericDataType

        def _column_dtype(col: Any) -> int:
            if getattr(col, "is_temporal", False):
                return GenericDataType.TEMPORAL
            if getattr(col, "is_numeric", False):
                return GenericDataType.NUMERIC
            # TODO: add check for boolean data type when proper support is added
            return GenericDataType.STRING

        return {
            "data": [
                {
                    "column_name": col.column_name,
                    "verbose_name": col.verbose_name,
                    "dtype": _column_dtype(col),
                }
                for col in getattr(self._datasource, "columns", []) or []
            ]
        }

    def _get_timegrains(self) -> dict[str, Any]:
        """Return the datasource's available time grains, no query executed."""
        return {
            "data": [
                {
                    "name": grain.name,
                    "function": grain.function,
                    "duration": grain.duration,
                }
                for grain in self._datasource.database.grains()  # type: ignore[attr-defined]
            ]
        }

    async def _get_query_only(self, query_object: AsyncQueryObject) -> dict[str, Any]:
        """Build SQL without executing — returns the query string only.

        Behavior:
          - the payload carries the datasource ``language`` (engine dialect,
            e.g. ``"sql"``) alongside ``query``, so the SQL-preview pane knows
            how to syntax-highlight it;
          - a build/validation error is surfaced *in the payload*
            (``error`` field) rather than raised — ``QueryObjectValidationError``
            (no SQL → just ``error``) and ``SupersetParseError`` (SQL generated
            but un-optimizable → both ``query`` and ``error``) are caught.
        """
        from superset.exceptions import (
            QueryObjectValidationError,
            SupersetParseError,
        )

        datasource = self._datasource
        query_dict = query_object.to_dict()

        # The payload carries only the engine ``language`` and the generated
        # ``query`` (plus an ``error`` field on failure). It deliberately does
        # NOT include the full-result keys (``status``, ``df``, ``data`` …) —
        # no query is executed for ``result_type=query``.
        result: dict[str, Any] = {
            "language": getattr(datasource, "query_language", None) or "sql",
        }

        # IMPORTANT: route through ``_build_sql`` (which calls
        # ``_adapt_query_dict_for_get_sqla_query`` first), NOT the raw
        # ``get_query_str`` → ``get_query_str_extended`` →
        # ``get_sqla_query(**query_dict)`` chain. The wire-format
        # ``query_dict`` carries keys that ``get_sqla_query`` doesn't
        # accept (``applied_time_extras``, ``filters``, ``url_params``,
        # ``custom_form_data`` …) — splatting them raises
        # ``TypeError: get_sqla_query() got an unexpected keyword
        # argument 'applied_time_extras'`` → 500. ``_build_sql`` adapts
        # the keys exactly like the execute path does, so ``type=query``
        # produces the same SQL the chart would actually run, run in a
        # worker thread (sync engine pipeline under asyncpg).
        try:
            if hasattr(datasource, "_build_sql"):
                sql, _from_dttm, _to_dttm = await asyncio.to_thread(
                    datasource._build_sql,
                    query_dict,
                    None,  # noqa: SLF001
                )
                result["query"] = sql
            elif hasattr(datasource, "get_query_str_extended"):
                extended = datasource.get_query_str_extended(query_dict)
                result["query"] = getattr(extended, "sql", str(extended))
            else:
                result["query"] = str(query_dict)
        except QueryObjectValidationError as err:
            # Validation error (missing required fields, invalid config) — no
            # SQL was generated, so only the error message is surfaced.
            result["error"] = getattr(err, "message", str(err))
        except SupersetParseError as err:
            # Parse/optimize error — SQL was generated but couldn't be
            # optimized; show both the SQL and the error.
            extra = getattr(getattr(err, "error", None), "extra", None)
            if extra and (sql := extra.get("sql")) is not None:
                result["query"] = sql
            result["error"] = getattr(err.error, "message", str(err))

        return result

    async def _get_samples(
        self,
        query_object: AsyncQueryObject,
        force: bool = False,
        force_cached: bool = False,
    ) -> dict[str, Any]:
        """Execute a simplified query for raw sample rows.

        Clear metrics/post-processing/orderby, populate ``columns`` with
        every physical column from the datasource, and drop the time
        window. Without populating ``columns`` the resulting query has no
        metrics and no columns, and ``get_sqla_query`` raises
        ``QueryObjectValidationError("Empty query?")``.
        """
        sample_qo = copy.deepcopy(query_object)
        sample_qo.is_timeseries = False
        sample_qo.orderby = []
        sample_qo.metrics = None
        sample_qo.post_processing = []
        qry_obj_cols: list[str] = []
        for o in getattr(self._datasource, "columns", []) or []:
            if isinstance(o, dict):
                col_name = o.get("column_name")
            else:
                col_name = getattr(o, "column_name", None)
            if col_name:
                qry_obj_cols.append(col_name)
        sample_qo.columns = qry_obj_cols
        sample_qo.from_dttm = None
        sample_qo.to_dttm = None
        if not sample_qo.row_limit:
            sample_qo.row_limit = getattr(self._settings, "samples_row_limit", 1000)

        return await self.get_df_payload(
            sample_qo,
            force=force,
            force_cached=force_cached,
            skip_post_processing=True,
        )

    async def _get_drill_detail(
        self,
        query_object: AsyncQueryObject,
        force: bool = False,
        force_cached: bool = False,
    ) -> dict[str, Any]:
        """Execute a drill-to-detail query.

        Differs from ``_get_samples`` in two ways:
          - the time filter is preserved (``from_dttm`` / ``to_dttm`` are NOT
            cleared), and
          - rows are ordered ascending by the first datasource column.
        Like samples it clears metrics/post-processing and selects every
        physical column.
        """
        # todo(yongjie): Remove this function,
        #  when determining whether samples should be applied to the time filter.
        drill_qo = copy.deepcopy(query_object)
        drill_qo.is_timeseries = False
        drill_qo.metrics = None
        drill_qo.post_processing = []
        qry_obj_cols: list[str] = []
        for o in getattr(self._datasource, "columns", []) or []:
            if isinstance(o, dict):
                col_name = o.get("column_name")
            else:
                col_name = getattr(o, "column_name", None)
            if col_name:
                qry_obj_cols.append(col_name)
        drill_qo.columns = qry_obj_cols
        drill_qo.orderby = [(drill_qo.columns[0], True)]

        return await self.get_df_payload(
            drill_qo,
            force=force,
            force_cached=force_cached,
        )

    async def get_df_payload(  # noqa: C901
        self,
        query_object: AsyncQueryObject,
        force: bool = False,
        force_cached: bool = False,
        skip_post_processing: bool = False,
    ) -> dict[str, Any]:
        """Execute a single query, return DataFrame + metadata."""
        from superset.exceptions import (
            InvalidPostProcessingError,
            QueryObjectValidationError,
        )

        # Validate query object (sanitize filters, check duplicates, etc.)
        # Pass the resolved ORM datasource so _sanitize_filters can render
        # Jinja templates in extras.where/having and sanitize the SQL clause.
        query_object.validate(datasource=self._datasource)

        # Validate columns exist in datasource (skip if no column metadata)
        ds_columns = getattr(self._datasource, "column_names", None)
        if ds_columns:
            from superset.utils.column import (
                get_column_names_from_columns,
                get_column_names_from_metrics,
            )

            requested_cols = get_column_names_from_columns(query_object.columns)
            requested_cols += get_column_names_from_metrics(query_object.metrics or [])
            invalid = [
                col
                for col in requested_cols
                if col not in ds_columns and col != DTTM_ALIAS
            ]
            if invalid:
                from superset.i18n import _

                raise QueryObjectValidationError(
                    _(
                        "Columns missing in dataset: %(invalid_columns)s",
                        invalid_columns=invalid,
                    )
                )

        cache_key = await self._get_cache_key(query_object)
        timeout = self._get_cache_timeout()

        # When the cache timeout chain returns -1 (CACHE_DISABLED_TIMEOUT),
        # the cache is bypassed entirely — both reads and writes.
        from superset.constants import CACHE_DISABLED_TIMEOUT

        force_query = force or timeout == CACHE_DISABLED_TIMEOUT

        cached_df: pd.DataFrame | None = None
        cached_annotation_data: dict[str, Any] = {}
        cached_applied_filter_columns: list[Any] = []
        cached_rejected_filter_columns: list[Any] = []
        cached_applied_template_filters: list[str] = []
        is_cached = False
        if self._cache_manager is not None and cache_key and not force_query:
            cached_result = await self._cache_get(cache_key)
            if cached_result is not None:
                if isinstance(cached_result, dict) and "df" in cached_result:
                    cached_df = cached_result["df"]
                    cached_annotation_data = cached_result.get("annotation_data", {})
                    cached_applied_filter_columns = list(
                        cached_result.get("applied_filter_columns") or []
                    )
                    cached_rejected_filter_columns = list(
                        cached_result.get("rejected_filter_columns") or []
                    )
                    cached_applied_template_filters = list(
                        cached_result.get("applied_template_filters") or []
                    )
                elif isinstance(cached_result, pd.DataFrame):
                    cached_df = cached_result
                if cached_df is not None:
                    is_cached = True

        if force_cached and not is_cached:
            return {
                "cache_key": cache_key,
                "error": "Cached data not available",
                "status": "failed",
                "is_cached": False,
                "df": pd.DataFrame(),
                "data": [],
                "rowcount": 0,
                "label_map": {},
                "applied_filters": [],
                "rejected_filters": [],
                "coltypes": [],
            }

        error_message: str | None = None
        query_str = ""
        status = "success"
        df: pd.DataFrame

        result: dict[str, Any] | None = None
        annotation_data: dict[str, Any] = cached_annotation_data
        if cached_df is not None:
            df = cached_df
            # Annotation data is stored alongside df in cache — skip re-fetch
        else:
            from superset.utils.date import (
                TimeDeltaAmbiguousError,
                TimeRangeAmbiguousError,
            )

            try:
                result = await self._get_query_result(
                    query_object,
                    skip_post_processing=skip_post_processing,
                )
                df = result.get("df", pd.DataFrame())
                query_str = result.get("query", "")

                # Surface a failed query (SQL error, "Empty query?", etc.) as a
                # failed payload — caught below → status="failed" + error, which
                # the command turns into a 400. Otherwise an errored query would
                # silently return 200 + empty df.
                if result.get("status") in ("error", "failed") or result.get(
                    "error_message"
                ):
                    raise QueryObjectValidationError(
                        result.get("error_message") or "Query failed"
                    )

                if query_object.time_offsets:
                    time_offset_result = await self.processing_time_offsets(
                        df, query_object
                    )
                    df = time_offset_result["df"]
                    offset_queries = time_offset_result["queries"]
                    if offset_queries:
                        query_str += ";\n\n"
                        query_str += ";\n\n".join(offset_queries)
                        query_str += ";\n\n"

                # Post-processing runs after time_offsets so it can operate
                # on the joined, shifted DataFrame. Skipped for ``results`` /
                # ``samples`` result types where the caller opted out.
                if not skip_post_processing and not df.empty:
                    try:
                        df = await asyncio.to_thread(
                            self._exec_post_processing, df, query_object
                        )
                    except InvalidPostProcessingError as ex:
                        # A bad post-processing op surfaces as a
                        # ``QueryObjectValidationError`` (caught below → a
                        # status=failed payload carrying the validation
                        # message), not a generic execution error.
                        raise QueryObjectValidationError(ex.message) from ex

                annotation_data = await self.get_annotation_data(query_object)

                if self._cache_manager is not None and cache_key:
                    cache_payload = {
                        "df": df,
                        "annotation_data": annotation_data,
                        "applied_filter_columns": list(
                            result.get("applied_filter_columns") or []
                        ),
                        "rejected_filter_columns": list(
                            result.get("rejected_filter_columns") or []
                        ),
                        "applied_template_filters": list(
                            result.get("applied_template_filters") or []
                        ),
                    }
                    await self._cache_set(cache_key, cache_payload, timeout)
            except (TimeDeltaAmbiguousError, TimeRangeAmbiguousError):
                # Ambiguous time-offset/range input is a user validation error;
                # propagate it instead of swallowing it into a
                # status=failed payload.
                raise
            except Exception as ex:
                logger.exception("Query execution failed")
                df = pd.DataFrame()
                # Sanitise the SA-2.0 + asyncpg ``<class '…'>:`` prefix and
                # the ``\n[SQL: …]\n[parameters: …]`` block ``str(exc)``
                # appends — without this the user-visible chart-data
                # ``error`` field leaks the DBAPI exception-class repr
                # AND the bound parameter values to the frontend toast.
                _raw = str(ex).split("\n[SQL:")[0].strip()
                import re as _re

                error_message = _re.sub(r"<class '[^']+'>:\s*", "", _raw)
                status = "failed"

        # The N-dimensional DataFrame has been flattened by the ``flatten``
        # operator, escaping commas inside column names via
        # ``escape_separator``; the result columns must be unescaped and each
        # flattened label split back into its component dimension/metric
        # labels. Adhoc columns/metrics additionally map to their SQL
        # expression rather than their label.
        from superset.utils.column import (
            get_column_name,
            get_column_names,
            get_metric_names,
            is_adhoc_column,
            is_adhoc_metric,
        )
        from superset.utils.core import (
            ExtraFiltersReasonType,
            get_time_filter_status,
        )
        from superset.utils.pandas_postprocessing.utils import unescape_separator

        label_map = {
            unescape_separator(col): [
                unescape_separator(c) for c in re.split(r"(?<!\\),\s", col)
            ]
            for col in df.columns.values
        }

        # Adhoc column/metric expression keys arrive in either camelCase
        # (raw request) or snake_case (after msgspec ``rename="camel"``
        # normalization), so read both — matching the dual-key convention
        # in ``utils/column.py`` (see [[feedback_camelcase_snake]]).
        def _adhoc_expr(obj: Any) -> Any:
            return obj.get("sqlExpression") or obj.get("sql_expression")

        def _adhoc_expr_type(obj: Any) -> Any:
            return obj.get("expressionType") or obj.get("expression_type")

        column_names = get_column_names(query_object.columns)
        label_map.update(
            {
                column_name: [
                    (
                        str(query_object.columns[idx])
                        if not is_adhoc_column(query_object.columns[idx])
                        else _adhoc_expr(query_object.columns[idx])
                    ),
                ]
                for idx, column_name in enumerate(column_names)
            }
        )
        metric_names = get_metric_names(query_object.metrics or [])
        label_map.update(
            {
                metric_name: [
                    (
                        str(query_object.metrics[idx])
                        if not is_adhoc_metric(query_object.metrics[idx])
                        else (
                            str(_adhoc_expr(query_object.metrics[idx]))
                            if _adhoc_expr_type(query_object.metrics[idx]) == "SQL"
                            else metric_name
                        )
                    ),
                ]
                for idx, metric_name in enumerate(metric_names)
                if query_object and query_object.metrics
            }
        )
        df.columns = [unescape_separator(col) for col in df.columns.values]

        # Compute coltypes from DataFrame dtypes + datasource column metadata
        coltypes = self._extract_coltypes(df, self._datasource)

        applied_filter_columns_meta: list[Any] = list(cached_applied_filter_columns)
        rejected_filter_columns_meta: list[Any] = list(cached_rejected_filter_columns)
        applied_template_filters_meta: list[str] = list(cached_applied_template_filters)
        if result is not None:
            applied_filter_columns_meta = list(
                result.get("applied_filter_columns") or []
            )
            rejected_filter_columns_meta = list(
                result.get("rejected_filter_columns") or []
            )
            applied_template_filters_meta = list(
                result.get("applied_template_filters") or []
            )

        applied_time_columns, rejected_time_columns = get_time_filter_status(
            self._datasource, dict(query_object.applied_time_extras or {})
        )
        applied_filters = [
            {"column": get_column_name(col)} for col in applied_filter_columns_meta
        ] + applied_time_columns
        rejected_filters = [
            {
                "reason": ExtraFiltersReasonType.COL_NOT_IN_DATASOURCE,
                "column": get_column_name(col),
            }
            for col in rejected_filter_columns_meta
        ] + rejected_time_columns

        return {
            "cache_key": cache_key,
            "cached_dttm": None,
            "cache_timeout": timeout,
            "df": df,
            "applied_template_filters": applied_template_filters_meta,
            "annotation_data": annotation_data,
            "error": error_message,
            "is_cached": is_cached,
            "query": query_str,
            "status": status,
            "stacktrace": None,
            "rowcount": len(df.index),
            "sql_rowcount": len(df.index),
            "from_dttm": query_object.from_dttm,
            "to_dttm": query_object.to_dttm,
            "label_map": label_map,
            "coltypes": coltypes,
            "applied_filters": applied_filters,
            "rejected_filters": rejected_filters,
            "result_format": getattr(query_object, "result_format", None) or "json",
        }

    async def _get_cache_key(
        self,
        query_object: AsyncQueryObject,
        time_offset: str | None = None,
    ) -> str:
        """Generate cache key from datasource.uid + RLS + query params.

        ``time_offset`` is folded into the key so each time-comparison offset
        subquery caches under a DISTINCT key — without it two offsets whose
        shifted clones happened to hash alike could collide and serve stale
        comparison data.
        """
        datasource = self._datasource
        extra_cache_keys = (
            datasource.get_extra_cache_keys(query_object.to_dict())
            if hasattr(datasource, "get_extra_cache_keys")
            else []
        )
        rls_key = await self._security_manager.get_rls_cache_key(
            datasource, user=self._user
        )

        cache_dict = query_object.cache_key()
        if time_offset is not None:
            cache_dict["time_offset"] = time_offset
        cache_dict.update(
            {
                "datasource": getattr(datasource, "uid", str(id(datasource))),
                "extra_cache_keys": extra_cache_keys,
                "rls": rls_key,
                "changed_on": getattr(datasource, "changed_on", None),
            }
        )
        # CACHE_IMPERSONATION additionally requires the database to actually
        # impersonate users, and the value comes from the engine-spec
        # ``get_impersonation_key`` (overridable per dialect) rather than a
        # bare username.
        if hasattr(self._settings, "feature_flags"):
            flags = self._settings.feature_flags or {}
            try:
                database = datasource.database  # type: ignore[attr-defined]
                if (
                    flags.get("CACHE_IMPERSONATION")
                    and getattr(database, "impersonate_user", False)
                ) or flags.get("CACHE_QUERY_BY_USER"):
                    if key := database.db_engine_spec.get_impersonation_key(self._user):
                        logger.debug(
                            "Adding impersonation key to QueryObject cache dict: %s",
                            key,
                        )
                        cache_dict["impersonation_key"] = key
            except AttributeError:
                # datasource or database do not exist
                pass

        return _generate_cache_key(cache_dict, "df-")

    async def _get_query_result(  # noqa: C901
        self,
        query_object: AsyncQueryObject,
        skip_post_processing: bool = False,
    ) -> dict[str, Any]:
        """Execute a query against the datasource, returning result dict."""
        datasource = self._datasource
        query_dict = query_object.to_dict()

        # Gather RLS clauses with group_key OR/AND grouping and Jinja
        # templating semantics (see ``BaseDatasource.get_sqla_row_level_filters``).
        from sqlalchemy.sql.elements import ClauseElement

        from superset.utils.rls import compose_rls_where_clauses

        rls_clauses: list[ClauseElement] = []
        if hasattr(self._security_manager, "get_rls_filters"):
            rls_clauses = await compose_rls_where_clauses(
                self._datasource,
                user=self._user,
                security_manager=self._security_manager,
            )

        if hasattr(datasource, "async_query"):
            if rls_clauses:
                result = await datasource.async_query(
                    query_dict, rls_filters=rls_clauses
                )
            else:
                result = await datasource.async_query(query_dict)
        elif hasattr(datasource, "query"):
            if rls_clauses:
                result = await asyncio.to_thread(  # type: ignore[call-arg]
                    datasource.query, query_dict, rls_filters=rls_clauses
                )
            else:
                result = await asyncio.to_thread(datasource.query, query_dict)
        else:
            # Defensive catch-all for any datasource that exposes neither
            # ``async_query`` nor ``query``. SqlaTable and (since
            # ``datasource_type="query"`` was wired) ``Query`` both implement
            # ``async_query``, so this is unreachable for them — it remains a
            # clean 4xx for any future interface-less datasource instead of an
            # opaque 500 (UNKNOWN_ERROR).
            from superset.exceptions import QueryObjectValidationError

            raise QueryObjectValidationError(
                "This datasource does not support charting. Save the data as a "
                "dataset (virtual dataset) to chart it."
            )

        applied_filter_columns: list[Any] = []
        rejected_filter_columns: list[Any] = []
        applied_template_filters: list[str] = []
        query_status: Any = "success"
        query_error: str | None = None

        if hasattr(result, "df"):
            df = result.df
            query_str = getattr(result, "query", "")
            query_status = getattr(result, "status", "success") or "success"
            query_error = getattr(result, "error_message", None)
            applied_filter_columns = list(
                getattr(result, "applied_filter_columns", []) or []
            )
            rejected_filter_columns = list(
                getattr(result, "rejected_filter_columns", []) or []
            )
            applied_template_filters = list(
                getattr(result, "applied_template_filters", []) or []
            )
        elif isinstance(result, dict):
            df = result.get("df", pd.DataFrame())
            query_str = result.get("query", "")
            query_status = result.get("status", "success") or "success"
            query_error = result.get("error_message")
            applied_filter_columns = list(
                result.get("applied_filter_columns", []) or []
            )
            rejected_filter_columns = list(
                result.get("rejected_filter_columns", []) or []
            )
            applied_template_filters = list(
                result.get("applied_template_filters", []) or []
            )
        else:
            df = pd.DataFrame()
            query_str = ""

        if not df.empty:
            # Always only *normalize* here. Post-processing is applied by
            # ``get_df_payload`` AFTER ``processing_time_offsets`` has had a
            # chance to join the time-shifted columns onto the DataFrame.
            df = await asyncio.to_thread(self._normalize_df, df, query_object)

        return {
            "df": df,
            "query": query_str,
            "status": query_status,
            "error_message": query_error,
            "applied_filter_columns": applied_filter_columns,
            "rejected_filter_columns": rejected_filter_columns,
            "applied_template_filters": applied_template_filters,
        }

    def _normalize_df(  # noqa: C901
        self, df: pd.DataFrame, query_object: AsyncQueryObject
    ) -> pd.DataFrame:
        """Replace inf/-inf with NaN and normalize datetime/metric columns.

        Uses get_base_axis_labels() + datasource.get_column() to build proper
        DateColumn objects with python_date_format, offset, time_shift.
        Handles DTTM_ALIAS via DateColumn.get_legacy_time_column().
        """
        from superset.utils.column import get_base_axis_labels, get_metric_names
        from superset.utils.dataframe import df_metrics_to_num, normalize_dttm_col
        from superset.utils.date import DateColumn

        def _get_timestamp_format(column: str | None) -> str | None:
            if not hasattr(self._datasource, "get_column"):
                return None
            column_obj = self._datasource.get_column(column)
            if (
                column_obj
                # only sqla column was supported
                and not isinstance(column_obj, dict)
                and (formatter := getattr(column_obj, "python_date_format", None))
            ):
                return str(formatter)
            return None

        date_columns: list[DateColumn] = []

        # Handle DTTM_ALIAS (legacy time column). Seed the legacy column's
        # ``timestamp_format`` from the *granularity* column's
        # ``python_date_format`` so epoch_s / epoch_ms / custom-strftime
        # temporal columns are converted correctly.
        if DTTM_ALIAS in df.columns:
            date_columns.append(
                DateColumn.get_legacy_time_column(
                    timestamp_format=_get_timestamp_format(query_object.granularity),
                    offset=getattr(self._datasource, "offset", None),
                    time_shift=query_object.time_shift,
                )
            )

        seen_labels = {DTTM_ALIAS}
        base_labels = [*get_base_axis_labels(query_object.columns)]
        if query_object.granularity:
            base_labels.append(query_object.granularity)
        for label in base_labels:
            if label in df.columns and label not in seen_labels:
                col_obj = (
                    self._datasource.get_column(label)
                    if hasattr(self._datasource, "get_column")
                    else None
                )
                # Only normalize a base-axis label when its datasource column
                # is temporal (``is_dttm``). Without this guard a categorical/
                # numeric x-axis that happens to be in ``df.columns`` is fed to
                # ``pd.to_datetime(errors="coerce")`` and corrupted to NaT.
                if not col_obj:
                    continue
                is_dttm = (
                    col_obj.get("is_dttm")
                    if isinstance(col_obj, dict)
                    else getattr(col_obj, "is_dttm", False)
                )
                if not is_dttm:
                    continue
                seen_labels.add(label)
                date_columns.append(
                    DateColumn(
                        col_label=label,
                        timestamp_format=_get_timestamp_format(label),
                        offset=getattr(self._datasource, "offset", None),
                        time_shift=query_object.time_shift,
                    )
                )

        # Fallback: check column specs directly for dttm columns
        if not date_columns:
            for col_spec in query_object.columns:
                if isinstance(col_spec, dict) and col_spec.get("is_dttm"):
                    col_name = col_spec.get("label") or col_spec.get(
                        "sqlExpression", ""
                    )
                    if col_name in df.columns and col_name not in seen_labels:
                        seen_labels.add(col_name)
                        date_columns.append(
                            DateColumn(
                                col_label=col_name,
                                timestamp_format=None,
                                offset=getattr(self._datasource, "offset", None),
                                time_shift=query_object.time_shift,
                            )
                        )

        if date_columns:
            normalize_dttm_col(df, tuple(date_columns))

        if self.enforce_numerical_metrics and query_object.metrics:
            metric_names = get_metric_names(query_object.metrics)
            df_metrics_to_num(df, metric_names)

        # Replace inf/-inf LAST, after normalize_dttm_col + df_metrics_to_num.
        # Doing it first would miss any inf produced by ``df_metrics_to_num``
        # (e.g. a ratio metric), leaving non-JSON-serialisable infinities in
        # the result.
        df = df.replace([np.inf, -np.inf], np.nan)

        return df

    def _normalize_and_postprocess(
        self, df: pd.DataFrame, query_object: AsyncQueryObject
    ) -> pd.DataFrame:
        """Normalize then apply post-processing. Runs in a worker thread."""
        df = self._normalize_df(df, query_object)
        df = self._exec_post_processing(df, query_object)
        return df

    @staticmethod
    def _extract_coltypes(
        df: pd.DataFrame,
        datasource: Any | None = None,
    ) -> list[int]:
        """Map DataFrame column types to GenericDataType enum values.

        Three datasource-aware operations:
        1. Build ``columns_by_name`` from ``datasource.columns`` — each entry
           may be a dict or a column object with ``.column_name`` /
           ``.is_dttm`` attributes.
        2. For all-NaN series, consult ``datasource.columns_types`` (a
           ``{column_name: sql_type}`` dict) and map via
           ``_map_sql_type_to_inferred_type``; fall back to
           ``_get_metric_type_from_column`` if the column name is not found in
           ``columns_types``.
        3. For each column, if the matching datasource column has
           ``is_dttm == True``, classify as TEMPORAL regardless of pandas dtype.
        """
        from pandas.api.types import infer_dtype

        from superset.typing import GenericDataType

        inferred_type_map: dict[str, GenericDataType] = {
            "floating": GenericDataType.NUMERIC,
            "integer": GenericDataType.NUMERIC,
            "mixed-integer-float": GenericDataType.NUMERIC,
            "decimal": GenericDataType.NUMERIC,
            "boolean": GenericDataType.BOOLEAN,
            "datetime64": GenericDataType.TEMPORAL,
            "datetime": GenericDataType.TEMPORAL,
            "date": GenericDataType.TEMPORAL,
        }

        columns_by_name: dict[str, Any] = {}
        if datasource:
            for column in getattr(datasource, "columns", None) or []:
                if isinstance(column, dict):
                    columns_by_name[column.get("column_name")] = column  # type: ignore[index]
                else:
                    columns_by_name[getattr(column, "column_name", None)] = (  # type: ignore[index]
                        column
                    )

        generic_types: list[int] = []
        for column in df.columns:
            column_object = columns_by_name.get(column)
            series = df[column]
            inferred_type: str = ""
            if series.isna().all():
                sql_type: str | None = ""
                if datasource and hasattr(datasource, "columns_types"):
                    columns_types = datasource.columns_types
                    if column in columns_types:
                        sql_type = columns_types.get(column)
                        inferred_type = (
                            AsyncQueryContextProcessor._map_sql_type_to_inferred_type(
                                sql_type,
                            )
                        )
                    else:
                        inferred_type = (
                            AsyncQueryContextProcessor._get_metric_type_from_column(
                                column, datasource
                            )
                        )
            else:
                inferred_type = infer_dtype(series)
            if isinstance(column_object, dict):
                generic_type = (
                    GenericDataType.TEMPORAL
                    if column_object and column_object.get("is_dttm")
                    else inferred_type_map.get(inferred_type, GenericDataType.STRING)
                )
            else:
                generic_type = (
                    GenericDataType.TEMPORAL
                    if column_object and getattr(column_object, "is_dttm", False)
                    else inferred_type_map.get(inferred_type, GenericDataType.STRING)
                )
            generic_types.append(generic_type)

        return generic_types

    @staticmethod
    def _map_sql_type_to_inferred_type(sql_type: str | None) -> str:
        """Map a SQL type to a pandas inferred-type string."""
        if not sql_type:
            return "string"
        _type_mapping = {
            re.compile(r"INT", re.IGNORECASE): "integer",
            re.compile(r"CHAR|TEXT|VARCHAR", re.IGNORECASE): "string",
            re.compile(r"DECIMAL|NUMERIC|FLOAT|DOUBLE", re.IGNORECASE): "floating",
            re.compile(r"BOOL", re.IGNORECASE): "boolean",
            re.compile(r"DATE|TIME", re.IGNORECASE): "datetime64",
        }
        for pattern, inferred_type in _type_mapping.items():
            if pattern.search(sql_type):
                return inferred_type
        return "string"

    @staticmethod
    def _get_metric_type_from_column(column: Any, datasource: Any) -> str:
        """Determine the metric type from a column name and datasource."""
        _metric_map_type: dict[str, str] = {
            "SUM": "floating",
            "AVG": "floating",
            "COUNT": "floating",
            "COUNT_DISTINCT": "floating",
            "MIN": "numeric",
            "MAX": "numeric",
            "FIRST": "string",
            "LAST": "string",
            "GROUP_CONCAT": "string",
        }

        metrics = getattr(datasource, "metrics", None) or []
        metric = next(
            (m for m in metrics if getattr(m, "metric_name", None) == column),
            None,
        )
        if metric is None:
            return ""

        expression: str = getattr(metric, "expression", "") or ""
        if not expression:
            return ""

        match = re.match(
            r"(SUM|AVG|COUNT|COUNT_DISTINCT|MIN|MAX|FIRST|LAST)\((.*)\)",
            expression,
        )
        if match:
            operation = match.group(1)
            return _metric_map_type.get(operation, "")

        logger.warning("Unexpected metric expression type: %s", expression)
        return ""

    @staticmethod
    def _exec_post_processing(
        df: pd.DataFrame,
        query_object: AsyncQueryObject,
    ) -> pd.DataFrame:
        """Apply post-processing operations on the DataFrame.

        This is a synchronous method (pandas operations are CPU-bound).
        Called via asyncio.to_thread() to avoid blocking the event loop.
        """
        if not query_object.post_processing:
            return df

        if pandas_postprocessing is None:
            raise ImportError(
                "superset.utils.pandas_postprocessing is not available; "
                "post-processing operations cannot be applied."
            )

        from superset.exceptions import InvalidPostProcessingError
        from superset.i18n import _

        # A missing ``operation`` key or an unsupported operation raises
        # ``InvalidPostProcessingError`` with these exact messages, which the
        # caller re-raises as ``QueryObjectValidationError``.
        for operation in query_object.post_processing:
            op_name = operation.get("operation")
            op_options = operation.get("options", {})
            if not op_name:
                raise InvalidPostProcessingError(
                    _("`operation` property of post processing object undefined")
                )
            if not hasattr(pandas_postprocessing, op_name):
                raise InvalidPostProcessingError(
                    _(
                        "Unsupported post processing operation: %(operation)s",
                        operation=op_name,
                    )
                )
            func = getattr(pandas_postprocessing, op_name)
            df = func(df, **op_options)
        return df

    @staticmethod
    def get_time_grain(query_object: AsyncQueryObject) -> Any | None:
        if (
            query_object.columns
            and len(query_object.columns) > 0
            and isinstance(query_object.columns[0], dict)
        ):
            # Support both camelCase and snake_case payload conventions.
            return query_object.columns[0].get("timeGrain") or query_object.columns[
                0
            ].get("time_grain")
        return query_object.extras.get("time_grain_sqla")

    def _get_cache_timeout(self) -> int:
        """Get cache timeout — priority chain:

        1. custom_cache_timeout (from query context)
        2. slice_.cache_timeout (chart-level)
        3. datasource.cache_timeout (dataset-level)
        4. datasource.database.cache_timeout (database-level)
        5. data_cache_config["CACHE_DEFAULT_TIMEOUT"]
        6. settings.cache_default_timeout
        """
        if self._query_context is not None:
            custom = getattr(self._query_context, "custom_cache_timeout", None)
            if custom is not None:
                return custom
            slice_ = getattr(self._query_context, "slice_", None)
            if slice_ and getattr(slice_, "cache_timeout", None):
                return slice_.cache_timeout
        if (
            hasattr(self._datasource, "cache_timeout")
            and self._datasource.cache_timeout
        ):
            return self._datasource.cache_timeout
        if hasattr(self._datasource, "database"):
            db = self._datasource.database
            if hasattr(db, "cache_timeout") and db.cache_timeout:
                return db.cache_timeout
        data_cache_config = getattr(self._settings, "data_cache_config", {})
        if isinstance(data_cache_config, dict):
            timeout = data_cache_config.get("CACHE_DEFAULT_TIMEOUT")
            if timeout is not None:
                return timeout
        return getattr(self._settings, "cache_default_timeout", 300)

    def _generate_context_cache_key(self) -> str:
        cache_dict: dict[str, Any] = {
            "datasource": getattr(self._datasource, "uid", ""),
        }
        if self._query_context is not None:
            cache_dict["queries"] = [qo.to_dict() for qo in self._query_context.queries]
            cache_dict["form_data"] = self._query_context.form_data
        return _generate_cache_key(cache_dict, "qc-")

    async def _cache_get(self, key: str) -> Any | None:
        """Retrieve cached data (DataFrame or dict with df+annotation_data).

        Values are stored as pickle bytes by ``_cache_set``, so we
        deserialize them here before returning.
        """
        if self._cache_manager is None:
            return None
        try:
            if hasattr(self._cache_manager, "get"):
                getter = self._cache_manager.get(key)
                result = await getter if inspect.isawaitable(getter) else getter
                if result is not None:
                    try:
                        import pickle  # noqa: S403

                        return pickle.loads(result)  # noqa: S301
                    except (pickle.UnpicklingError, TypeError, EOFError):
                        logger.warning(
                            "Cache unpickle failed for key %s, returning raw value",
                            key,
                        )
                        return result
        except Exception:  # noqa: BLE001
            logger.warning("Cache get failed for key %s", key, exc_info=True)
        return None

    async def _cache_set(self, key: str, value: Any, timeout: int) -> None:
        """Store a value (DataFrame or dict) in cache.

        Serializes the value to bytes via pickle before passing to the cache
        manager, which expects ``bytes``.  Pickle is used here (rather than
        JSON) because the cached values may contain pandas DataFrames and
        NumPy arrays.

        Skip the write when timeout == CACHE_DISABLED_TIMEOUT so that datasets
        with caching disabled never populate the cache store.
        """
        if self._cache_manager is None:
            return
        from superset.constants import CACHE_DISABLED_TIMEOUT

        if timeout == CACHE_DISABLED_TIMEOUT:
            return
        try:
            import pickle  # noqa: S403

            serialized = pickle.dumps(value, protocol=pickle.HIGHEST_PROTOCOL)
            if hasattr(self._cache_manager, "set"):
                setter = self._cache_manager.set(key, serialized, timeout)
                if inspect.isawaitable(setter):
                    await setter
        except (TypeError, pickle.PicklingError):
            logger.warning("Cache serialization failed for key %s", key, exc_info=True)
        except Exception:
            logger.warning("Cache set failed for key %s", key, exc_info=True)

    async def get_annotation_data(
        self, query_object: AsyncQueryObject
    ) -> dict[str, Any]:
        annotation_data: dict[str, Any] = await self.get_native_annotation_data(
            query_object
        )
        for annotation_layer in [
            layer
            for layer in query_object.annotation_layers
            if layer.get("sourceType") in ("line", "table")
        ]:
            name = annotation_layer["name"]
            annotation_data[name] = await self.get_viz_annotation_data(
                annotation_layer,
                force=getattr(self._query_context, "force", False),
                _depth=self._recursion_depth,
            )
        return annotation_data

    async def get_native_annotation_data(
        self, query_object: AsyncQueryObject
    ) -> dict[str, Any]:
        annotation_data: dict[str, Any] = {}
        annotation_layers = [
            layer
            for layer in query_object.annotation_layers
            if layer.get("sourceType") == "NATIVE"
        ]
        if not annotation_layers or self._annotation_dao is None:
            return annotation_data

        layer_ids = [layer["value"] for layer in annotation_layers]
        layer_objects_list = await self._annotation_dao.find_by_ids(layer_ids)
        layer_objects = {lo.id: lo for lo in layer_objects_list}

        for layer in annotation_layers:
            layer_id = layer["value"]
            layer_name = layer["name"]
            columns = [
                "start_dttm",
                "end_dttm",
                "short_descr",
                "long_descr",
                "json_metadata",
            ]
            layer_object = layer_objects.get(layer_id)
            if layer_object is None:
                continue
            records = [
                {column: getattr(annotation, column) for column in columns}
                for annotation in layer_object.annotation
            ]
            annotation_data[layer_name] = {"columns": columns, "records": records}
        return annotation_data

    async def get_viz_annotation_data(  # noqa: C901
        self,
        annotation_layer: dict[str, Any],
        force: bool,
        _depth: int = 0,
    ) -> dict[str, Any]:
        """Fetch annotation data from another chart (recursive).

        Depth limit prevents infinite recursion when charts reference each other.
        This method:
        - raises QueryObjectValidationError (not ValueError) for user-visible
          errors (chart not found, missing datasource, missing query context)
        - wraps the entire execution in try/except SupersetException so
          internal errors are sanitized before surfacing to the user
        - calls raise_for_access on the annotation processor to enforce
          RBAC on the annotation chart's datasource
        """
        from superset.exceptions import (
            QueryObjectValidationError,
            SupersetException,
        )
        from superset.i18n import _
        from superset.utils.core import error_msg_from_exception

        if _depth >= _MAX_RECURSION_DEPTH:
            raise QueryObjectValidationError(
                f"Annotation recursion depth exceeded (max={_MAX_RECURSION_DEPTH})"
            )

        if self._chart_dao is None:
            raise QueryObjectValidationError(
                _("Chart DAO not available for annotations")
            )

        chart = await self._chart_dao.find_by_id(annotation_layer["value"])
        if not chart:
            raise QueryObjectValidationError(
                _(
                    "Chart with ID %(chart_id)s (referenced by "
                    "annotation layer '%(layer_name)s') was not found. "
                    "Please verify that the chart exists and is accessible.",
                    chart_id=annotation_layer["value"],
                    layer_name=annotation_layer["name"],
                )
            )

        try:
            # Legacy viz_type charts (e.g. "line", "area", "pie") are served via
            # ``BaseViz.get_payload()``; modern charts go through
            # ``chart.get_query_context()`` → ``AsyncQueryContextProcessor``.
            # ``viz_types`` is imported lazily here to avoid a circular-import
            # at load time.
            from superset.viz import get_active_viz_types  # noqa: PLC0415

            chart_viz_type = getattr(chart, "viz_type", None)
            # Denylist-filtered registry — a VIZ_TYPE_DENYLIST'd type must NOT
            # be routed into the legacy BaseViz pipeline here.
            if chart_viz_type in get_active_viz_types():
                if not getattr(chart, "datasource", None):
                    raise QueryObjectValidationError(
                        _(
                            "The dataset for chart ID %(chart_id)s (referenced by "
                            "annotation layer '%(layer_name)s') was not "
                            "found. Please check that the dataset exists and is "
                            "accessible.",
                            chart_id=chart.id,
                            layer_name=annotation_layer["name"],
                        )
                    )
                from superset.viz import get_viz as _get_viz  # noqa: PLC0415

                form_data = chart.form_data.copy() if chart.form_data else {}
                form_data.update(annotation_layer.get("overrides", {}))
                viz_obj = _get_viz(
                    datasource=chart.datasource,
                    form_data=form_data,
                    force=force,
                )
                payload = await viz_obj.get_payload()
                return payload.get("data") or []  # type: ignore[return-value]

            get_qc = getattr(chart, "get_query_context", None)
            if get_qc is None:
                raise QueryObjectValidationError(
                    _(
                        "The query context for chart ID %(chart_id)s (referenced "
                        "by annotation layer '%(layer_name)s') was not found. "
                        "Please ensure the chart is properly configured and has "
                        "a valid query context.",
                        chart_id=chart.id,
                        layer_name=annotation_layer["name"],
                    )
                )
            query_context = get_qc()
            if not query_context:
                raise QueryObjectValidationError(
                    _(
                        "The query context for chart ID %(chart_id)s (referenced "
                        "by annotation layer '%(layer_name)s') was not found. "
                        "Please ensure the chart is properly configured and has "
                        "a valid query context.",
                        chart_id=chart.id,
                        layer_name=annotation_layer["name"],
                    )
                )

            # Apply annotation overrides to query objects
            overrides = annotation_layer.get("overrides", {})
            if overrides and query_context.queries:
                time_range = overrides.get("time_range")
                if time_range:
                    from superset.utils.date import get_since_until_from_time_range

                    from_dttm, to_dttm = get_since_until_from_time_range(
                        time_range=time_range
                    )
                for qo in query_context.queries:
                    if time_grain_sqla := overrides.get("time_grain_sqla"):
                        qo.extras["time_grain_sqla"] = time_grain_sqla
                    if time_range:
                        qo.from_dttm = from_dttm
                        qo.to_dttm = to_dttm

            # Set force on the annotation query_context so that
            # processing_time_offsets() inside the annotation processor
            # reads self._query_context.force correctly when force=True.
            query_context.force = force

            # Build a new processor scoped to the annotation chart's datasource.
            # Using self._datasource here would produce wrong cache keys and
            # access checks (the annotation source may be a different dataset).
            annotation_datasource = getattr(chart, "datasource", self._datasource)
            annotation_processor = AsyncQueryContextProcessor(
                datasource=annotation_datasource,
                settings=self._settings,
                security_manager=self._security_manager,
                user=self._user,
                cache_manager=self._cache_manager,
                annotation_dao=self._annotation_dao,
                chart_dao=self._chart_dao,
                query_context=query_context,
                _recursion_depth=_depth + 1,
            )

            # ``raise_for_access`` is called on the annotation chart's
            # datasource. Without this, a user could access data from
            # datasets they don't have permission for.
            await annotation_processor.raise_for_access()

            payload = await annotation_processor.get_payload(
                query_objects=query_context.queries, force=force
            )
            # ``get_df_payload`` stores the result as ``{"df": df, ...}``; the
            # ``df -> data`` conversion normally happens in the chart controller
            # (_render_chart_data_payload), which is NOT invoked in this
            # annotation path.  We must replicate the conversion here so that
            # ``payload["queries"][0]["data"]`` is populated before reading it.
            q = payload["queries"][0]
            if isinstance(q, dict) and isinstance(q.get("df"), pd.DataFrame):
                df = q.pop("df")
                q["data"] = df.to_dict(orient="records")
            return {"records": q.get("data", [])}
        except SupersetException as ex:
            raise QueryObjectValidationError(error_msg_from_exception(ex)) from ex

    async def processing_time_offsets(  # noqa: C901
        self,
        df: pd.DataFrame,
        query_object: AsyncQueryObject,
    ) -> CachedTimeOffset:
        """Process time-shifted comparisons (e.g., '1 week ago', '1 year ago').

        For each time_offset, clones the query with shifted time range,
        executes it, renames metric columns with the offset suffix, and
        joins the offset DataFrames with the original on non-metric columns.
        """
        queries: list[str] = []
        cache_keys: list[str | None] = []

        if not query_object.time_offsets:
            return CachedTimeOffset(df=df, queries=queries, cache_keys=cache_keys)

        # Mirrors ``get_since_until_from_query_object``:
        # ``query_object.time_range`` takes precedence, otherwise fall back to
        # scanning ``query_object.filters`` for a ``TEMPORAL_RANGE`` entry.
        # The Explore UI emits time filters as adhoc TEMPORAL_RANGE entries
        # rather than top-level ``time_range``.
        outer_from_dttm = query_object.from_dttm
        outer_to_dttm = query_object.to_dttm

        if not outer_from_dttm or not outer_to_dttm:
            from superset.utils.date import get_since_until_from_time_range

            resolved_time_range: str | None = query_object.time_range
            if not resolved_time_range:
                # Iterates ALL filters and keeps the LAST TEMPORAL_RANGE match
                # (no early break) — matters only when a query carries multiple
                # TEMPORAL_RANGE filters.
                for flt in query_object.filters or []:
                    if (
                        isinstance(flt, dict)
                        and flt.get("op") == "TEMPORAL_RANGE"
                        and isinstance(flt.get("val"), str)
                    ):
                        resolved_time_range = flt["val"]

            # Pass ``extras`` so config relative-time anchors + per-request
            # overrides are honored when resolving the offset outer bounds
            # (bare ``get_since_until`` hardcodes ``today`` → wrong shifted window).
            since, until = get_since_until_from_time_range(
                resolved_time_range,
                query_object.time_shift,
                query_object.extras,
            )
            outer_from_dttm = outer_from_dttm or since
            outer_to_dttm = outer_to_dttm or until

        if not outer_from_dttm or not outer_to_dttm:
            from superset.exceptions import QueryObjectValidationError

            raise QueryObjectValidationError(
                "An enclosed time range (both start and end) must be specified "
                "when using a Time Comparison."
            )

        from superset.utils.column import get_metric_names

        metric_names = get_metric_names(query_object.metrics)
        join_keys = [col for col in df.columns if col not in metric_names]
        time_comparison_sep = "__"
        time_grain = self.get_time_grain(query_object)

        offset_dfs: dict[str, pd.DataFrame] = {}

        from superset.exceptions import QueryObjectValidationError
        from superset.utils.column import get_base_axis_labels, get_x_axis_label
        from superset.utils.date import (
            get_past_or_future,
            get_since_until_from_time_range,
        )
        from superset.utils.feature_flags import feature_flag_manager

        for offset in query_object.time_offsets:
            original_offset = offset
            is_date_range_offset = self._is_valid_date_range(offset)

            query_object_clone = copy.deepcopy(query_object)

            if is_date_range_offset:
                # Absolute date-range offset ("2015-01-03 : 2015-01-04"); gated
                # behind DATE_RANGE_TIMESHIFTS_ENABLED.
                if not feature_flag_manager.is_feature_enabled(
                    "DATE_RANGE_TIMESHIFTS_ENABLED"
                ):
                    raise QueryObjectValidationError(
                        "Date range timeshifts are not enabled. Please contact "
                        "your administrator to enable the "
                        "DATE_RANGE_TIMESHIFTS_ENABLED feature flag."
                    )
                try:
                    offset_from_dttm, offset_to_dttm = get_since_until_from_time_range(
                        time_range=offset
                    )
                except ValueError as ex:
                    raise QueryObjectValidationError(str(ex)) from ex
                # Use the explicit range directly; inner bounds would add a
                # conflicting WHERE clause.
                query_object_clone.from_dttm = offset_from_dttm
                query_object_clone.to_dttm = offset_to_dttm
                query_object_clone.inner_from_dttm = None
                query_object_clone.inner_to_dttm = None
            else:
                # Relative offset. Resolve ``inherit`` / explicit-date offsets to
                # a "N days ago" string (``original_offset`` keeps the label).
                if offset == "inherit" or self._is_valid_date(offset):
                    offset = self._get_offset_custom_or_inherit(
                        offset,
                        outer_from_dttm,
                        outer_to_dttm,
                    )
                query_object_clone.from_dttm = get_past_or_future(
                    offset,
                    outer_from_dttm,  # type: ignore[arg-type]
                )
                query_object_clone.to_dttm = get_past_or_future(
                    offset,
                    outer_to_dttm,  # type: ignore[arg-type]
                )
                query_object_clone.inner_from_dttm = query_object_clone.from_dttm
                query_object_clone.inner_to_dttm = query_object_clone.to_dttm

            x_axis_label = get_x_axis_label(query_object.columns)
            query_object_clone.granularity = (
                query_object_clone.granularity or x_axis_label
            )
            query_object_clone.time_offsets = []
            query_object_clone.post_processing = []

            # Adjust the temporal filter so the shifted query runs over the
            # correct window (the comparison may not be on a temporal column,
            # so the TEMPORAL_RANGE filter must follow the shift).
            index = (get_base_axis_labels(query_object.columns) or [DTTM_ALIAS])[0]
            if is_date_range_offset:
                new_filters = [
                    flt
                    for flt in copy.deepcopy(query_object_clone.filters)
                    if not (isinstance(flt, dict) and flt.get("op") == "TEMPORAL_RANGE")
                ]
                temporal_col = self._get_temporal_column_for_filter(
                    query_object_clone, x_axis_label
                )
                if not temporal_col:
                    raise QueryObjectValidationError(
                        "Unable to identify temporal column for date range time "
                        "comparison. Please ensure your dataset has a properly "
                        "configured time column."
                    )
                new_filters.append(
                    {
                        "col": temporal_col,
                        "op": "TEMPORAL_RANGE",
                        "val": (
                            f"{query_object_clone.from_dttm} : "
                            f"{query_object_clone.to_dttm}"
                        ),
                    }
                )
                query_object_clone.filters = new_filters
            elif not self._is_datetime_series(df.get(index)):
                # Non-datetime x-axis: shift the existing TEMPORAL_RANGE filter's
                # range string by the offset.
                new_filters = copy.deepcopy(query_object_clone.filters)
                for flt in new_filters:
                    if (
                        isinstance(flt, dict)
                        and flt.get("op") == "TEMPORAL_RANGE"
                        and isinstance(flt.get("val"), str)
                    ):
                        new_from, new_to = get_since_until_from_time_range(
                            time_range=flt["val"], time_shift=offset
                        )
                        flt["val"] = f"{new_from} : {new_to}"
                query_object_clone.filters = new_filters
            else:
                # Datetime x-axis: align the matching TEMPORAL_RANGE filter with
                # the shifted from/to.
                new_filters = copy.deepcopy(query_object_clone.filters)
                temporal_col = query_object_clone.granularity or x_axis_label
                for flt in new_filters:
                    if (
                        isinstance(flt, dict)
                        and flt.get("op") == "TEMPORAL_RANGE"
                        and flt.get("col") == temporal_col
                    ):
                        flt["val"] = (
                            f"{query_object_clone.from_dttm} : "
                            f"{query_object_clone.to_dttm}"
                        )
                query_object_clone.filters = new_filters

            # Drop non-temporal x-axis filters (keep temporal ones).
            query_object_clone.filters = [
                flt
                for flt in query_object_clone.filters
                if not (
                    isinstance(flt, dict)
                    and flt.get("col") == x_axis_label
                    and flt.get("op") != "TEMPORAL_RANGE"
                )
            ]

            # When the original query has a limit/offset, cap the offset
            # subquery at ROW_LIMIT (NOT unbounded) and drop the offset — 1:1
            # with upstream — so the join isn't skewed by missing records, while
            # still bounding the subquery. The port previously forced
            # ``row_limit = None`` → an UNBOUNDED offset subquery.
            if query_object.row_limit or query_object.row_offset:
                query_object_clone.row_limit = int(
                    getattr(self._settings, "row_limit", 50000)
                )
                query_object_clone.row_offset = 0

            # Per-offset cache: look up this offset's result under an
            # offset-distinct key before recomputing. The key folds in the
            # RESOLVED+original offset and the time grain so distinct offsets
            # never collide. ``force`` bypasses the read (always recompute).
            cached_time_offset_key = (
                offset if offset == original_offset else f"{offset}_{original_offset}"
            )
            offset_cache_key = await self._get_cache_key(
                query_object_clone,
                time_offset=f"{cached_time_offset_key}|{time_grain}",
            )
            force = bool(getattr(self._query_context, "force", False))
            cached_offset = None if force else await self._cache_get(offset_cache_key)
            if isinstance(cached_offset, dict) and "df" in cached_offset:
                offset_dfs[offset] = cached_offset["df"]
                queries.append(cached_offset.get("query", ""))
                cache_keys.append(offset_cache_key)
                continue

            # A failed offset query propagates (raises out of
            # ``processing_time_offsets`` → main query fails) instead of
            # silently producing NaN comparison columns.
            result = await self._get_query_result(query_object_clone)
            if result.get("status") in ("error", "failed") or result.get(
                "error_message"
            ):
                from superset.exceptions import QueryObjectValidationError

                raise QueryObjectValidationError(
                    result.get("error_message") or "Time-offset query failed"
                )
            offset_metrics_df = result.get("df", pd.DataFrame())
            queries.append(result.get("query", ""))
            cache_keys.append(None)

            # Rename metric columns with the USER-FACING (original) offset.
            metrics_mapping = {
                metric: time_comparison_sep.join([metric, original_offset])
                for metric in metric_names
            }

            if offset_metrics_df.empty:
                # Build the empty-offset placeholder with each join key typed to
                # match the MAIN frame (so a temporal join column becomes ``NaT``,
                # not a float ``NaN``). Upstream relied on older pandas coercing a
                # datetime64-vs-float64 merge; SQLAlchemy/pandas 2.x raises, so we
                # keep the dtypes consistent for the join in ``join_offset_dfs``.
                placeholder: dict[str, Any] = {}
                for col in join_keys:
                    dtype = df[col].dtype if col in df.columns else None
                    placeholder[col] = pd.Series([np.nan], dtype=dtype)
                for col in metrics_mapping.values():
                    placeholder[col] = [np.nan]
                offset_metrics_df = pd.DataFrame(placeholder)
            else:
                offset_metrics_df = self._normalize_df(
                    offset_metrics_df, query_object_clone
                )
                offset_metrics_df = offset_metrics_df.rename(columns=metrics_mapping)

            await self._cache_set(
                offset_cache_key,
                {"df": offset_metrics_df, "query": result.get("query", "")},
                self._get_cache_timeout(),
            )

            # Key by the RESOLVED offset so ``join_offset_dfs`` shifts the join
            # column by the real time delta.
            offset_dfs[offset] = offset_metrics_df

        if offset_dfs:
            df = self.join_offset_dfs(df, offset_dfs, time_grain, join_keys)

        return CachedTimeOffset(df=df, queries=queries, cache_keys=cache_keys)

    def join_offset_dfs(
        self,
        df: pd.DataFrame,
        offset_dfs: dict[str, pd.DataFrame],
        time_grain: str | None,
        join_keys: list[str],
    ) -> pd.DataFrame:
        """Join offset DataFrames with the main DataFrame.

        For a temporal time grain the offset result is joined on a *bucketed +
        offset-shifted* temporal key (:meth:`generate_join_column`) so each main
        row aligns with the corresponding shifted offset row (e.g. "today" with
        "today − 1 year"); a plain merge on the raw timestamp would mis-align
        them.
        """
        from superset.utils.feature_flags import feature_flag_manager

        join_column_producer = None

        for offset, offset_df in offset_dfs.items():
            is_date_range_offset = self._is_valid_date_range(
                offset
            ) and feature_flag_manager.is_feature_enabled(
                "DATE_RANGE_TIMESHIFTS_ENABLED"
            )
            offset_df, actual_join_keys = self._determine_join_keys(
                df,
                offset_df,
                offset,
                time_grain,
                join_keys,
                is_date_range_offset,
                join_column_producer,
            )
            df = self._perform_join(df, offset_df, actual_join_keys)
            df = self._apply_cleanup_logic(
                df, offset, time_grain, join_keys, is_date_range_offset
            )

        return df

    def _determine_join_keys(
        self,
        df: pd.DataFrame,
        offset_df: pd.DataFrame,
        offset: str,
        time_grain: str | None,
        join_keys: list[str],
        is_date_range_offset: bool,
        join_column_producer: Any,
    ) -> tuple[pd.DataFrame, list[str]]:
        """For a temporal grain, add a synthetic offset-join column to both frames
        (the main frame shifted by ``offset``, the offset frame unshifted) and
        join on it instead of the raw timestamp.
        """
        if time_grain and not is_date_range_offset:
            column_name = OFFSET_JOIN_COLUMN_SUFFIX + offset
            self.add_offset_join_column(
                df, column_name, time_grain, offset, join_column_producer
            )
            self.add_offset_join_column(
                offset_df, column_name, time_grain, None, join_column_producer
            )
            return offset_df, [column_name, *join_keys[1:]]
        if is_date_range_offset:
            return self._process_date_range_offset(offset_df, join_keys)
        return offset_df, join_keys

    def add_offset_join_column(
        self,
        df: pd.DataFrame,
        name: str,
        time_grain: str,
        time_offset: str | None = None,
        join_column_producer: Any = None,
    ) -> None:
        """Add an offset join column to ``df`` in place."""
        if join_column_producer:
            df[name] = df.apply(lambda row: join_column_producer(row, 0), axis=1)
        else:
            df[name] = df.apply(
                lambda row: self.generate_join_column(row, 0, time_grain, time_offset),
                axis=1,
            )

    @staticmethod
    def generate_join_column(
        row: pd.Series,
        column_index: int,
        time_grain: str,
        time_offset: str | None = None,
    ) -> str:
        """Bucket (and optionally offset-shift) a temporal value into a join key."""
        from pandas import DateOffset

        from superset.utils.date import normalize_time_delta
        from superset.utils.pandas_postprocessing._constants import TimeGrain

        # ``.iloc`` = positional access (the original used ``row[column_index]``,
        # which newer pandas deprecates for integer keys); semantics identical.
        value = row.iloc[column_index]

        # An empty-offset placeholder row carries ``NaT`` for a temporal join
        # column (dtype-matched to the main frame). ``NaT`` has a ``strftime``
        # attribute but raises when called, so fall through to ``str(value)`` —
        # a sentinel key that never matches a real bucketed timestamp.
        if pd.isna(value):
            return str(value)

        if hasattr(value, "strftime"):
            if time_offset and not AsyncQueryContextProcessor._is_valid_date_range(
                time_offset
            ):
                value = value + DateOffset(**normalize_time_delta(time_offset))

            if time_grain in (
                TimeGrain.WEEK_STARTING_SUNDAY,
                TimeGrain.WEEK_ENDING_SATURDAY,
            ):
                return value.strftime("%Y-W%U")
            if time_grain in (
                TimeGrain.WEEK,
                TimeGrain.WEEK_STARTING_MONDAY,
                TimeGrain.WEEK_ENDING_SUNDAY,
            ):
                return value.strftime("%Y-W%W")
            if time_grain == TimeGrain.MONTH:
                return value.strftime("%Y-%m")
            if time_grain == TimeGrain.QUARTER:
                return value.strftime("%Y-Q") + str(value.quarter)
            if time_grain == TimeGrain.YEAR:
                return value.strftime("%Y")

        return str(value)

    def _perform_join(
        self,
        df: pd.DataFrame,
        offset_df: pd.DataFrame,
        actual_join_keys: list[str],
    ) -> pd.DataFrame:
        """Left-join ``offset_df`` onto ``df``."""
        if actual_join_keys:
            return df.merge(
                offset_df,
                on=actual_join_keys,
                how="left",
                suffixes=("", R_SUFFIX),
            )
        temp_key = "__temp_join_key__"
        df = df.copy()
        offset_df = offset_df.copy()
        df[temp_key] = 1
        offset_df[temp_key] = 1
        result_df = df.merge(
            offset_df,
            on=[temp_key],
            how="left",
            suffixes=("", R_SUFFIX),
        )
        result_df.drop(columns=[temp_key], inplace=True, errors="ignore")
        result_df.drop(columns=[f"{temp_key}{R_SUFFIX}"], inplace=True, errors="ignore")
        return result_df

    @staticmethod
    def _apply_cleanup_logic(
        df: pd.DataFrame,
        offset: str,
        time_grain: str | None,
        join_keys: list[str],
        is_date_range_offset: bool,
    ) -> pd.DataFrame:
        """Drop the synthetic join column + right-suffix columns and restore
        column order."""
        if time_grain and not is_date_range_offset:
            if join_keys:
                col = df.pop(join_keys[0])
                df.insert(0, col.name, col)
            df.drop(
                list(df.filter(regex=f"{OFFSET_JOIN_COLUMN_SUFFIX}|{R_SUFFIX}")),
                axis=1,
                inplace=True,
            )
        else:
            df.drop(
                list(df.filter(regex=f"{R_SUFFIX}")),
                axis=1,
                inplace=True,
            )
        return df

    @staticmethod
    def _is_datetime_series(series: Any) -> bool:
        """Return True when the series contains datetime-like values."""
        import datetime as _dt

        if series is None or not isinstance(series, pd.Series):
            return False
        if series.isnull().all():
            return False
        return pd.api.types.is_datetime64_any_dtype(series) or (
            series.apply(lambda x: isinstance(x, _dt.date) or x is None).all()
        )

    @staticmethod
    def _is_valid_date(date_string: str) -> bool:
        from datetime import datetime as _datetime

        try:
            _datetime.strptime(date_string, "%Y-%m-%d")
            return True
        except ValueError:
            return False

    @staticmethod
    def _is_valid_date_range(date_range: str) -> bool:
        from datetime import datetime as _datetime

        try:
            start_date, end_date = date_range.split(":")
            _datetime.strptime(start_date.strip(), "%Y-%m-%d")
            _datetime.strptime(end_date.strip(), "%Y-%m-%d")
            return True
        except ValueError:
            return False

    def _get_offset_custom_or_inherit(
        self,
        offset: str,
        outer_from_dttm: Any,
        outer_to_dttm: Any,
    ) -> str:
        """Resolve ``inherit`` / explicit-date offsets to a ``N days ago`` string."""
        from datetime import datetime as _datetime

        if offset == "inherit":
            return f"{(outer_to_dttm - outer_from_dttm).days} days ago"
        if self._is_valid_date(offset):
            offset_date = _datetime.strptime(offset, "%Y-%m-%d")
            return f"{(outer_from_dttm - offset_date).days} days ago"
        return ""

    def _get_temporal_column_for_filter(
        self, query_object: AsyncQueryObject, x_axis_label: str | None
    ) -> str | None:
        """Best-effort temporal column for date-range filtering: explicit
        granularity → x-axis label → first ``is_dttm`` datasource column."""
        if query_object.granularity:
            return query_object.granularity
        if x_axis_label:
            return x_axis_label
        for col in getattr(self._datasource, "columns", []) or []:
            if getattr(col, "is_dttm", False):
                name = getattr(col, "column_name", None) or getattr(col, "name", None)
                if name:
                    return name
        return None

    @staticmethod
    def _process_date_range_offset(
        offset_df: pd.DataFrame,
        join_keys: list[str],
    ) -> tuple[pd.DataFrame, list[str]]:
        """Aggregate the date-range offset frame when only temporal join keys remain."""
        temporal_cols = ["ds", "__timestamp", "dttm"]
        non_temporal_join_keys = [k for k in join_keys if k not in temporal_cols]
        if non_temporal_join_keys:
            return offset_df, non_temporal_join_keys
        metric_columns = [c for c in offset_df.columns if c not in temporal_cols]
        if metric_columns:
            aggregated_values: dict[str, Any] = {}
            for col in metric_columns:
                if pd.api.types.is_numeric_dtype(offset_df[col]):
                    aggregated_values[col] = offset_df[col].sum()
                else:
                    aggregated_values[col] = (
                        offset_df[col].iloc[0] if not offset_df.empty else None
                    )
            offset_df = pd.DataFrame([aggregated_values])
        return offset_df, []

    async def raise_for_access(self) -> None:
        """Validate per-query and delegate to
        AsyncSecurityManager.raise_for_access().
        """
        # Validate each query object before access check
        if self._query_context is not None:
            for query in self._query_context.queries:
                query.validate(datasource=self._datasource)

        if getattr(self._datasource, "type", None) == "query":
            await self._security_manager.raise_for_access(
                query=self._datasource, user=self._user
            )
        else:
            await self._security_manager.raise_for_access(
                query_context=self._query_context, user=self._user
            )

    @staticmethod
    def get_data(
        df: pd.DataFrame,
        result_format: str = "json",
        coltypes: list[int] | None = None,
        verbose_map: dict[str, str] | None = None,
    ) -> Any:
        """Convert DataFrame to the requested result format.

        - The verbose column-name map (datasource ``data["verbose_map"]``)
          renames physical column names to their human-readable label, so
          the export uses the same headers the user sees in the chart.
        - CSV is written via ``csv.df_to_escaped_csv(df, **CSV_EXPORT)`` —
          the ``CSV_EXPORT`` config (default ``{"encoding": "utf-8-sig"}``)
          sets the separator/encoding/etc. that pandas applies.
        - XLSX runs ``excel.apply_column_types(df, coltypes)`` first (so
          numerics export as numbers, tz-aware datetimes as strings) and is
          then written via ``excel.df_to_excel(df, **EXCEL_EXPORT)``.

        ``coltypes`` are computed from the DataFrame dtypes when not supplied;
        ``verbose_map`` is applied when supplied (the export path threads it in
        from the datasource).
        """
        if result_format in ("csv", "xlsx"):
            from superset import config as _config
            from superset.utils import csv as _csv, excel as _excel

            # DataFrames with custom indices (e.g., after pivot/groupby)
            # include the index as a column in the export.
            include_index = not isinstance(df.index, pd.RangeIndex)

            if verbose_map:
                df.columns = [verbose_map.get(col, col) for col in df.columns]

            try:
                settings = _config.SupersetSettings()  # type: ignore[call-arg]
                csv_export = dict(getattr(settings, "csv_export", {}) or {})
                excel_export = dict(getattr(settings, "excel_export", {}) or {})
            except Exception:  # noqa: BLE001 — never break export on config errors
                csv_export, excel_export = {"encoding": "utf-8-sig"}, {}

            if result_format == "csv":
                return _csv.df_to_escaped_csv(df, index=include_index, **csv_export)

            # XLSX — apply column types before writing (numerics → numbers,
            # tz-aware datetimes → strings), matching upstream order.
            if coltypes is None:
                coltypes = AsyncQueryContextProcessor._extract_coltypes(df)
            _excel.apply_column_types(df, coltypes)  # type: ignore[arg-type]
            return _excel.df_to_excel(df, **excel_export)

        # Serialize datetime columns as epoch milliseconds. Chart components on
        # the frontend expect numeric timestamps so they can format them
        # with ``smart_date`` / ``time_grain_sqla`` (e.g. "2008 Q1").
        if df.empty:
            return []

        df_out = df
        dttm_cols = [
            col
            for col in df.columns
            if pd.api.types.is_datetime64_any_dtype(df[col].dtype)
        ]
        if dttm_cols:
            df_out = df.copy()
            for col in dttm_cols:
                series = df_out[col]
                # nanoseconds since epoch → milliseconds (float)
                ms = series.astype("int64", copy=False).astype("float64") / 1_000_000
                # Preserve NaT as None
                mask = series.isna()
                if mask.any():
                    ms = ms.where(~mask, other=None)
                df_out[col] = ms
        return df_out.to_dict(orient="records")
